---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - xz-utils
    state: present

- name: Add Puppet Labs apt key.
  apt_key:
    url: https://apt.puppetlabs.com/DEB-GPG-KEY-puppet-20250406
    state: present

- name: Add Puppet Labs repository.
  apt:
    deb: "{{ puppet_apt_deb }}"
    state: present
  register: puppet_apt_deb_install

- name: Update apt cache if necessary.
  apt: update_cache=true
  when: puppet_apt_deb_install.changed
  tags: ['skip_ansible_lint']
