---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # Debian based.
    - name: Set the java_packages variable.
      set_fact:
        java_packages:
          - openjdk-11-jdk
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
      when: ansible_os_family == 'Debian'
    - role: geerlingguy.puppet
