---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache if necessary.
      apt: update_cache=true cache_valid_time=300
      when: ansible_facts.os_family == 'Debian'

  roles:
    - role: geerlingguy.java
      when: ansible_facts.os_family == 'Debian'
    - role: geerlingguy.puppet
