---
- name: Converge
  hosts: all
  #become: true

  vars:
    java_packages:
      - openjdk-17-jdk

  roles:
    - role: geerlingguy.java
      when: ansible_os_family == 'Debian'
    - role: geerlingguy.puppet
