---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    # Debian or Ubuntu
    - name: Set the java_packages variable.
      ansible.builtin.set_fact:
        java_packages:
          - openjdk-11-jdk
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  roles:
    - role: geerlingguy.java
      when: ansible_os_family == 'Debian'
    - role: geerlingguy.puppet
